import {
  Property, Holding, Payout, Developer, MarketListing,
  AppNotification, BankAccount, Transaction, KYCStatus, FAQItem,
  P2PTrade, MyListing,
} from './types';

export const properties: Property[] = [
  {
    id: '1',
    name: 'Gwarinpa Luxury Duplex',
    type: 'rental',
    status: 'active',
    phase: 'renting',
    location: { state: 'FCT', city: 'Abuja', area: 'Gwarinpa' },
    developer: { id: 'd1', name: 'Saleem Goje Properties', initials: 'SG' },
    image: '',
    totalValue: 90_000_000,
    unitPrice: 150_000,
    totalUnits: 600,
    unitsSold: 432,
    investorCount: 432,
    annualRent: 4_200_000,
    rentYield: 8.5,
    description:
      'This stunning 4-bedroom duplex in Gwarinpa features modern finishes, 24-hour power supply, and is in one of Abuja\'s most sought-after residential areas. Fully tenanted with a verified annual rent of N4.2M.',
  },
  {
    id: '2',
    name: 'Kuje Estate Phase 2',
    type: 'build_sell',
    status: 'active',
    phase: 'construction',
    constructionProgress: 35,
    location: { state: 'FCT', city: 'Abuja', area: 'Kuje' },
    developer: { id: 'd2', name: 'Dan Mama Homes', initials: 'DM' },
    image: '',
    totalValue: 250_000_000,
    unitPrice: 50_000,
    totalUnits: 5000,
    unitsSold: 2250,
    investorCount: 890,
    estimatedProfit: 40,
    timelineMonths: 18,
    description:
      'A 10-unit estate development in Kuje. Construction is 35% complete. Estimated sale price N350M — giving investors approximately 40% return on investment over 18 months.',
  },
  {
    id: '3',
    name: 'Jabi Lake Terraces',
    type: 'rental',
    status: 'active',
    phase: 'renting',
    location: { state: 'FCT', city: 'Abuja', area: 'Jabi' },
    developer: { id: 'd1', name: 'Saleem Goje Properties', initials: 'SG' },
    image: '',
    totalValue: 150_000_000,
    unitPrice: 250_000,
    totalUnits: 600,
    unitsSold: 540,
    investorCount: 540,
    annualRent: 12_000_000,
    rentYield: 10.2,
    description:
      'Premium 3-block terrace apartments overlooking Jabi Lake. Each block has 4 units. Currently generating N12M annual rent with 98% occupancy rate.',
  },
  {
    id: '4',
    name: 'Maitama Commercial Plot',
    type: 'land',
    status: 'active',
    phase: 'holding',
    location: { state: 'FCT', city: 'Abuja', area: 'Maitama' },
    developer: { id: 'd2', name: 'Dan Mama Homes', initials: 'DM' },
    image: '',
    totalValue: 500_000_000,
    unitPrice: 200_000,
    totalUnits: 2500,
    unitsSold: 625,
    investorCount: 420,
    pricePerSqm: 50_000,
    totalAreaSqm: 10_000,
    description:
      '2.5 hectares of prime commercial land in Maitama. Currently valued at N50,000/sqm with 15% annual appreciation in the area.',
  },
  {
    id: '5',
    name: 'Wuse 2 Smart Homes',
    type: 'build_sell',
    status: 'active',
    phase: 'funding',
    constructionProgress: 0,
    location: { state: 'FCT', city: 'Abuja', area: 'Wuse 2' },
    developer: { id: 'd1', name: 'Saleem Goje Properties', initials: 'SG' },
    image: '',
    totalValue: 180_000_000,
    unitPrice: 75_000,
    totalUnits: 2400,
    unitsSold: 480,
    investorCount: 280,
    estimatedProfit: 35,
    timelineMonths: 14,
    description:
      '6-unit smart home development in Wuse 2. Features home automation, solar power, and modern design. Early stage — 20% funded.',
  },
];

export const holdings: Holding[] = [
  {
    id: 'h1',
    property: properties[0],
    units: 4,
    investedAmount: 600_000,
    currentValue: 672_000,
    totalEarned: 28_000,
    nextPayoutAmount: 7_000,
    nextPayoutDays: 45,
  },
  {
    id: 'h2',
    property: properties[1],
    units: 20,
    investedAmount: 1_000_000,
    currentValue: 1_120_000,
    totalEarned: 0,
    nextPayoutAmount: 0,
    nextPayoutDays: 0,
  },
  {
    id: 'h3',
    property: properties[2],
    units: 3,
    investedAmount: 750_000,
    currentValue: 825_000,
    totalEarned: 48_000,
    nextPayoutAmount: 8_100,
    nextPayoutDays: 45,
  },
];

export const payouts: Payout[] = [
  { id: 'p1', propertyName: 'Gwarinpa Luxury Duplex', amount: 5_833, date: 'Apr 1, 2026', status: 'sent' },
  { id: 'p2', propertyName: 'Jabi Lake Terraces', amount: 8_100, date: 'Apr 1, 2026', status: 'sent' },
  { id: 'p3', propertyName: 'Gwarinpa Luxury Duplex', amount: 5_833, date: 'Jan 1, 2026', status: 'sent' },
  { id: 'p4', propertyName: 'Jabi Lake Terraces', amount: 8_100, date: 'Jan 1, 2026', status: 'sent' },
];

export const portfolioSummary = {
  totalInvested: 2_350_000,
  currentValue: 2_617_000,
  totalEarned: 76_000,
  gainPercent: 11.4,
};

// Developers
export const developers: Developer[] = [
  {
    id: 'd1',
    name: 'Saleem Goje Properties',
    initials: 'SG',
    bio: 'Award-winning real estate developer in Abuja with over 15 years of experience. Specializing in luxury residential and smart home developments across the FCT.',
    propertiesListed: 3,
    totalRaised: 420_000_000,
    investorCount: 2048,
    followerCount: 1250,
    isFollowing: true,
    propertyIds: ['1', '3', '5'],
  },
  {
    id: 'd2',
    name: 'Dan Mama Homes',
    initials: 'DM',
    bio: 'Leading property development firm focused on affordable housing estates and commercial land in Abuja. Known for on-time delivery and transparent communication.',
    propertiesListed: 2,
    totalRaised: 750_000_000,
    investorCount: 1310,
    followerCount: 890,
    isFollowing: false,
    propertyIds: ['2', '4'],
  },
  {
    id: 'd3',
    name: 'Pinnacle Estates',
    initials: 'PE',
    bio: 'Lagos-based luxury property developer with a focus on Ikoyi and Lekki. Over 20 completed projects and N15B in total development value.',
    propertiesListed: 0,
    totalRaised: 0,
    investorCount: 0,
    followerCount: 320,
    isFollowing: false,
    propertyIds: [],
  },
  {
    id: 'd4',
    name: 'Heritage Homes Nigeria',
    initials: 'HH',
    bio: 'Affordable housing developer in Abuja and Nasarawa. Committed to making homeownership accessible through fractional investment.',
    propertiesListed: 0,
    totalRaised: 0,
    investorCount: 0,
    followerCount: 150,
    isFollowing: false,
    propertyIds: [],
  },
  {
    id: 'd5',
    name: 'Zenith Land Partners',
    initials: 'ZL',
    bio: 'Specializing in strategic land banking across FCT and Lagos. Proven track record of 200%+ land appreciation in key growth corridors.',
    propertiesListed: 0,
    totalRaised: 0,
    investorCount: 0,
    followerCount: 580,
    isFollowing: true,
    propertyIds: [],
  },
  {
    id: 'd6',
    name: 'Kingsway Developments',
    initials: 'KD',
    bio: 'Mixed-use development specialist. From shopping plazas to residential complexes, delivering value across property classes in Port Harcourt.',
    propertiesListed: 0,
    totalRaised: 0,
    investorCount: 0,
    followerCount: 210,
    isFollowing: false,
    propertyIds: [],
  },
  {
    id: 'd7',
    name: 'Sahel Properties',
    initials: 'SP',
    bio: 'Northern Nigeria focused developer. Building modern estates in Kano, Kaduna, and Abuja with culturally sensitive designs.',
    propertiesListed: 0,
    totalRaised: 0,
    investorCount: 0,
    followerCount: 430,
    isFollowing: false,
    propertyIds: [],
  },
  {
    id: 'd8',
    name: 'GreenVille Realty',
    initials: 'GR',
    bio: 'Eco-friendly developer building sustainable, solar-powered communities in Lagos and Ibadan. Green building certified.',
    propertiesListed: 0,
    totalRaised: 0,
    investorCount: 0,
    followerCount: 670,
    isFollowing: false,
    propertyIds: [],
  },
];

// Secondary Market Listings
export const marketListings: MarketListing[] = [
  {
    id: 'ml1',
    propertyId: '1',
    propertyName: 'Gwarinpa Luxury Duplex',
    propertyType: 'rental',
    sellerName: 'Aminu K.',
    units: 3,
    askingPrice: 172_500,
    originalPrice: 150_000,
    gainPercent: 15,
    listedAt: 'Apr 28, 2026',
  },
  {
    id: 'ml2',
    propertyId: '3',
    propertyName: 'Jabi Lake Terraces',
    propertyType: 'rental',
    sellerName: 'Fatima O.',
    units: 5,
    askingPrice: 300_000,
    originalPrice: 250_000,
    gainPercent: 20,
    listedAt: 'Apr 25, 2026',
  },
  {
    id: 'ml3',
    propertyId: '2',
    propertyName: 'Kuje Estate Phase 2',
    propertyType: 'build_sell',
    sellerName: 'Ibrahim M.',
    units: 8,
    askingPrice: 47_500,
    originalPrice: 50_000,
    gainPercent: -5,
    listedAt: 'Apr 20, 2026',
  },
  {
    id: 'ml4',
    propertyId: '1',
    propertyName: 'Gwarinpa Luxury Duplex',
    propertyType: 'rental',
    sellerName: 'Hauwa B.',
    units: 2,
    askingPrice: 165_000,
    originalPrice: 150_000,
    gainPercent: 10,
    listedAt: 'Apr 18, 2026',
  },
  {
    id: 'ml5',
    propertyId: '4',
    propertyName: 'Maitama Commercial Plot',
    propertyType: 'land',
    sellerName: 'Yusuf A.',
    units: 4,
    askingPrice: 230_000,
    originalPrice: 200_000,
    gainPercent: 15,
    listedAt: 'Apr 15, 2026',
  },
];

// P2P Trades
export const p2pTrades: P2PTrade[] = [
  {
    id: 'trade1',
    listingId: 'my_sold1',
    propertyId: '1',
    propertyName: 'Gwarinpa Luxury Duplex',
    propertyType: 'rental',
    buyerId: 'buyer1',
    buyerName: 'Aisha T.',
    sellerId: 'current_user',
    sellerName: 'Muhammad S.',
    units: 2,
    pricePerUnit: 165_000,
    subtotal: 330_000,
    tradingFee: 3_300,
    buyerPaid: 333_300,
    sellerReceives: 326_700,
    status: 'completed',
    sellerBankName: 'First Bank',
    sellerAccountLast4: '5678',
    createdAt: 'Apr 20, 2026',
    paidAt: 'Apr 25, 2026',
    sellerPaidAt: 'Apr 25, 2026',
    completedAt: 'Apr 25, 2026',
  },
];

// My Listings (extended with status)
export const myListings: MyListing[] = [
  {
    id: 'my1',
    propertyName: 'Gwarinpa Luxury Duplex',
    propertyType: 'rental',
    units: 2,
    askingPrice: 172_500,
    originalPrice: 150_000,
    listedAt: 'Apr 28, 2026',
    views: 12,
    status: 'active',
  },
  {
    id: 'my_sold1',
    propertyName: 'Gwarinpa Luxury Duplex',
    propertyType: 'rental',
    units: 2,
    askingPrice: 165_000,
    originalPrice: 150_000,
    listedAt: 'Apr 20, 2026',
    views: 24,
    status: 'sold',
    soldAt: 'Apr 25, 2026',
    tradeId: 'trade1',
    netReceived: 326_700,
    buyerName: 'Aisha T.',
  },
];

// Notifications
export const notifications: AppNotification[] = [
  { id: 'n1', type: 'payout', title: 'Payout Received', body: 'You received N5,833 from Gwarinpa Luxury Duplex', read: false, createdAt: 'Apr 30, 2026', route: '/payouts' },
  { id: 'n2', type: 'payout', title: 'Payout Received', body: 'You received N8,100 from Jabi Lake Terraces', read: false, createdAt: 'Apr 30, 2026', route: '/payouts' },
  { id: 'n3', type: 'property', title: 'Almost Funded!', body: 'Jabi Lake Terraces is now 90% funded — only 150 units left', read: true, createdAt: 'Apr 28, 2026', route: '/property/3' },
  { id: 'n4', type: 'market', title: 'Listing Sold', body: 'Your 2 units of Gwarinpa Duplex sold for N110,000/unit', read: true, createdAt: 'Apr 25, 2026', route: '/market/my-listings' },
  { id: 'n5', type: 'property', title: 'New Property', body: 'Wuse 2 Smart Homes is now available for investment', read: true, createdAt: 'Apr 20, 2026', route: '/property/5' },
  { id: 'n6', type: 'system', title: 'KYC Approved', body: 'Your Tier 1 verification is complete. You can now invest up to N5,000,000', read: true, createdAt: 'Apr 15, 2026' },
  { id: 'n7', type: 'system', title: 'Welcome to PropVest!', body: 'Start your real estate investment journey today', read: true, createdAt: 'Apr 10, 2026' },
  { id: 'n8', type: 'payout', title: 'Payout Received', body: 'You received N5,833 from Gwarinpa Luxury Duplex', read: true, createdAt: 'Jan 1, 2026', route: '/payouts' },
  { id: 'n9', type: 'property', title: 'Construction Update', body: 'Kuje Estate Phase 2 construction is now 40% complete — on schedule for March 2027', read: false, createdAt: 'Apr 29, 2026', route: '/property/2' },
  { id: 'n10', type: 'market', title: 'Price Alert', body: 'Gwarinpa Duplex units now listed at ₦165,000 — below your purchase price of ₦150,000', read: false, createdAt: 'Apr 27, 2026', route: '/market' },
  { id: 'n11', type: 'payout', title: 'Payout Scheduled', body: 'Q2 2026 payout for Jabi Lake Terraces is being calculated. Expected by July 5.', read: false, createdAt: 'Apr 26, 2026', route: '/payouts' },
  { id: 'n12', type: 'property', title: 'New from Developer', body: 'Saleem Goje Properties just listed a new property: Asokoro Executive Villa', read: true, createdAt: 'Apr 22, 2026', route: '/property/5' },
  { id: 'n13', type: 'system', title: 'Upgrade to Tier 2', body: 'Verify your BVN to increase your investment limit to ₦25,000,000', read: true, createdAt: 'Apr 18, 2026' },
  { id: 'n14', type: 'market', title: 'Your Listing Viewed', body: 'Your Gwarinpa Duplex listing has been viewed 24 times this week', read: true, createdAt: 'Apr 16, 2026', route: '/market/my-listings' },
  { id: 'n15', type: 'property', title: 'Fully Funded!', body: 'Congratulations! Gwarinpa Luxury Duplex is now fully funded with 600 investors', read: true, createdAt: 'Apr 12, 2026', route: '/property/1' },
];

// Bank Accounts
export const bankAccounts: BankAccount[] = [
  { id: 'ba1', bankName: 'First Bank', accountNumber: '3012345678', accountName: 'Muhammad Sada Yusuf', isPrimary: true },
  { id: 'ba2', bankName: 'GTBank', accountNumber: '0123456789', accountName: 'Muhammad Sada Yusuf', isPrimary: false },
];

// Transactions
export const transactions: Transaction[] = [
  { id: 't1', type: 'investment', amount: 600_000, description: 'Invested in Gwarinpa Luxury Duplex (4 units)', date: 'Mar 1, 2026', status: 'completed' },
  { id: 't2', type: 'investment', amount: 1_000_000, description: 'Invested in Kuje Estate Phase 2 (20 units)', date: 'Mar 5, 2026', status: 'completed' },
  { id: 't3', type: 'investment', amount: 750_000, description: 'Invested in Jabi Lake Terraces (3 units)', date: 'Mar 10, 2026', status: 'completed' },
  { id: 't4', type: 'payout', amount: 7_000, description: 'Quarterly payout — Gwarinpa Luxury Duplex', date: 'Apr 1, 2026', status: 'completed' },
  { id: 't5', type: 'payout', amount: 8_100, description: 'Quarterly payout — Jabi Lake Terraces', date: 'Apr 1, 2026', status: 'completed' },
  { id: 't6', type: 'market_sell', amount: 330_000, description: 'Sold 2 units — Gwarinpa Duplex @ N165,000', date: 'Apr 25, 2026', status: 'completed' },
];

// KYC Status
export const kycStatus: KYCStatus = {
  tier: 'tier1',
  verifiedAt: 'Apr 15, 2026',
  bankAccount: bankAccounts[0],
  investmentLimit: 5_000_000,
};

// FAQs
export const faqs: FAQItem[] = [
  { question: 'What is PropVest?', answer: 'PropVest is a fractional real estate investment platform that allows you to own units in premium Nigerian properties. Each developer sets their own unit price, so you can find properties that match your budget.' },
  { question: 'How do I earn returns?', answer: 'For rental properties, you receive quarterly payouts proportional to your units. For build & sell properties, you earn when the property is sold. For land, you benefit from appreciation.' },
  { question: 'Is my investment safe?', answer: 'All properties are verified with valid C of O and Governor\'s Consent. Payments are processed through Paystack and go directly to the developer\'s bank account minus the platform fee.' },
  { question: 'How do I withdraw my payouts?', answer: 'Payouts are automatically sent to your linked bank account quarterly. You can manage your bank accounts in Settings.' },
  { question: 'What is the secondary market?', answer: 'The secondary market allows you to sell your units to other investors before maturity. You set your price, and buyers can purchase at market rates.' },
  { question: 'What are the fees?', answer: 'PropVest charges a 2% platform fee on investments. There is a 1% trading fee (max ₦5,000) on secondary market transactions. No hidden charges.' },
];
