import type { Announcement } from '@/lib/types';

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-001',
    title: 'Welcome to PropVest - Your Real Estate Investment Platform',
    body: 'We are thrilled to launch PropVest, Nigeria\'s premier fractional real estate investment platform. Start investing in premium properties across Abuja and Lagos with as little as N50,000. Our team is committed to making real estate accessible to every Nigerian.',
    type: 'broadcast',
    status: 'sent',
    sentBy: 'staff-002',
    sentAt: '2025-06-01T09:00:00.000Z',
    recipientCount: 1245,
    createdAt: '2025-05-28T14:00:00.000Z',
  },
  {
    id: 'ann-002',
    title: 'New Property Alert: Gwarinpa Luxury Duplex Now Live',
    body: 'Exciting news! Our latest property listing, the Gwarinpa Luxury Duplex, is now live on the platform. This 6-unit development in the heart of Gwarinpa Estate offers a projected annual yield of 14.5%. Units start at just N250,000. Don\'t miss this opportunity!',
    type: 'broadcast',
    status: 'sent',
    sentBy: 'staff-003',
    sentAt: '2025-06-21T10:00:00.000Z',
    recipientCount: 1380,
    createdAt: '2025-06-20T16:00:00.000Z',
  },
  {
    id: 'ann-003',
    title: 'Q4 2025 Payouts Processing - Important Information',
    body: 'Dear investors, your Q4 2025 rental income payouts are currently being processed. Payments will be disbursed to your registered bank accounts within 3-5 business days. Please ensure your bank details are up to date. Contact support if you have any questions.',
    type: 'targeted',
    targetFilter: 'investors_with_active_rental_properties',
    status: 'sent',
    sentBy: 'staff-004',
    sentAt: '2026-01-02T08:00:00.000Z',
    recipientCount: 523,
    createdAt: '2026-01-01T14:00:00.000Z',
  },
  {
    id: 'ann-004',
    title: 'KYC Upgrade Reminder - Unlock Higher Investment Limits',
    body: 'You are currently on Tier 1 KYC which limits your investments to N1,000,000. Upgrade to Tier 2 (BVN verification) or Tier 3 (NIN verification) to unlock higher limits and access premium properties. Upgrade now in your profile settings.',
    type: 'targeted',
    targetFilter: 'kyc_tier_1_investors',
    status: 'sent',
    sentBy: 'staff-008',
    sentAt: '2026-02-15T10:00:00.000Z',
    recipientCount: 187,
    createdAt: '2026-02-14T11:00:00.000Z',
  },
  {
    id: 'ann-005',
    title: 'P2P Trading is Now Live - Sell Your Units on the Secondary Market',
    body: 'We are excited to announce the launch of our peer-to-peer trading marketplace. You can now list your property units for sale to other investors on the platform. A 1% trading fee applies to all completed trades. Visit the P2P section in your dashboard to get started.',
    type: 'broadcast',
    status: 'sent',
    sentBy: 'staff-002',
    sentAt: '2025-09-01T09:00:00.000Z',
    recipientCount: 1650,
    createdAt: '2025-08-30T16:00:00.000Z',
  },
  {
    id: 'ann-006',
    title: 'Scheduled Maintenance - Saturday, May 3rd',
    body: 'We will be performing scheduled maintenance on Saturday, May 3rd from 2:00 AM to 6:00 AM WAT. During this time, the platform may be intermittently unavailable. All pending transactions will be processed once maintenance is complete. We apologize for any inconvenience.',
    type: 'broadcast',
    status: 'draft',
    createdAt: '2026-04-29T10:00:00.000Z',
  },
  {
    id: 'ann-007',
    title: 'Q1 2026 Payout Summary Available',
    body: 'Your Q1 2026 payout summary is now available in your dashboard. Log in to view your earnings breakdown by property, including rental income received, management fees, and your net payout amount. Payouts are being processed and will arrive within 5 business days.',
    type: 'targeted',
    targetFilter: 'investors_with_q1_2026_payouts',
    status: 'draft',
    createdAt: '2026-04-28T14:00:00.000Z',
  },
  {
    id: 'ann-008',
    title: 'Lagos Market Now Open - Lekki Gardens Phase 3',
    body: 'PropVest has expanded beyond Abuja! We are pleased to announce our first Lagos property listing: Lekki Gardens Phase 3 by Cappa & D\'Alberto. This build-to-sell development features 30 terraced duplexes with a projected 20% return. Invest from N200,000 per unit.',
    type: 'broadcast',
    status: 'sent',
    sentBy: 'staff-002',
    sentAt: '2025-11-10T09:00:00.000Z',
    recipientCount: 1890,
    createdAt: '2025-11-09T15:00:00.000Z',
  },
];
