import type { DeveloperPartner } from '@/lib/types';

export const mockDevelopers: DeveloperPartner[] = [
  {
    id: 'dev-001',
    companyName: 'Saleem Goje Properties',
    contactName: 'Saleem Goje',
    email: 'info@saleemgoje.com',
    phone: '+2348031234567',
    bio: 'Premier real estate developer in Abuja specializing in luxury residential estates and smart homes across the FCT. Over 15 years of delivering quality housing.',
    propertiesCount: 4,
    totalRaised: 520000000,
    totalInvestors: 312,
    followerCount: 1580,
    status: 'active',
    bankName: 'Zenith Bank',
    bankAccountNumber: '1012345678',
    bankAccountName: 'Saleem Goje Properties Ltd',
    createdAt: '2025-02-10T09:00:00.000Z',
  },
  {
    id: 'dev-002',
    companyName: 'Dan Mama Homes',
    contactName: 'Abdulrahman Dan Mama',
    email: 'contact@danmamahomes.com',
    phone: '+2348052345678',
    bio: 'Building affordable yet premium housing solutions for middle-income Nigerians. Focused on the Abuja metropolitan area with over 500 units delivered.',
    propertiesCount: 3,
    totalRaised: 380000000,
    totalInvestors: 245,
    followerCount: 920,
    status: 'active',
    bankName: 'GTBank',
    bankAccountNumber: '0234567890',
    bankAccountName: 'Dan Mama Homes Limited',
    createdAt: '2025-03-05T10:30:00.000Z',
  },
  {
    id: 'dev-003',
    companyName: 'Brains & Hammers',
    contactName: 'Adamu Idris',
    email: 'partnerships@brainsandhammers.com',
    phone: '+2348063456789',
    bio: 'One of Nigeria\'s leading real estate development companies with multiple estate projects across Abuja. Known for Life Camp, Galadimawa, and Apo developments.',
    propertiesCount: 2,
    totalRaised: 680000000,
    totalInvestors: 489,
    followerCount: 3250,
    status: 'active',
    bankName: 'First Bank',
    bankAccountNumber: '3045678901',
    bankAccountName: 'Brains & Hammers Ltd',
    createdAt: '2025-01-20T08:00:00.000Z',
  },
  {
    id: 'dev-004',
    companyName: 'Cappa & D\'Alberto',
    contactName: 'Emeka Nwosu',
    email: 'invest@cappadalbert.com',
    phone: '+2348074567890',
    bio: 'Historic Nigerian construction and development firm established in 1932. Renowned for iconic Lagos developments and expanding into the Abuja market.',
    propertiesCount: 1,
    totalRaised: 150000000,
    totalInvestors: 126,
    followerCount: 2100,
    status: 'active',
    bankName: 'UBA',
    bankAccountNumber: '2056789012',
    bankAccountName: 'Cappa & D\'Alberto Plc',
    createdAt: '2025-04-01T11:00:00.000Z',
  },
  {
    id: 'dev-005',
    companyName: 'Urban Shelter Ltd',
    contactName: 'Bala Mohammed',
    email: 'bala@urbanshelter.ng',
    phone: '+2348085678901',
    bio: 'Emerging real estate developer focused on modern urban living in Abuja. Currently preparing first listing on the PropVest platform.',
    propertiesCount: 0,
    totalRaised: 0,
    totalInvestors: 0,
    followerCount: 45,
    status: 'pending',
    bankName: 'Access Bank',
    bankAccountNumber: '0167890123',
    bankAccountName: 'Urban Shelter Limited',
    createdAt: '2026-03-20T14:00:00.000Z',
  },
];
