import type { Property } from '@/lib/types';

export const mockProperties: Property[] = [
  // ── RENTAL PROPERTIES ──────────────────────────────────
  {
    id: 'prop-001',
    name: 'Gwarinpa Luxury Duplex',
    type: 'rental',
    status: 'active',
    phase: 'renting', // Built, tenanted, generating rent
    location: { state: 'FCT', city: 'Abuja', area: 'Gwarinpa' },
    developerId: 'dev-001',
    developerName: 'Saleem Goje Properties',
    totalValue: 180000000,
    unitPrice: 250000,
    totalUnits: 720,
    unitsSold: 485,
    investorCount: 142,
    yield: '14.5%',
    description: 'A 6-unit luxury duplex development in the heart of Gwarinpa Estate, Abuja. Each unit features 4 bedrooms, modern finishes, smart home integration, and dedicated parking. Fully tenanted with corporate clients on long-term leases.',
    platformFeePercent: 3,
    managementFeePercent: 10,
    paystackSubaccountCode: 'ACCT_gwarinpa001',
    dvaAccountNumber: '9900012345',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Certificate of Occupancy', url: '/docs/prop-001/cofo.pdf', type: 'legal' },
      { name: 'Building Plan Approval', url: '/docs/prop-001/plan.pdf', type: 'legal' },
      { name: 'Valuation Report', url: '/docs/prop-001/valuation.pdf', type: 'financial' },
    ],
    images: ['/images/prop-001/main.jpg', '/images/prop-001/interior.jpg', '/images/prop-001/exterior.jpg'],
    createdAt: '2025-06-15T10:00:00.000Z',
    approvedAt: '2025-06-20T14:30:00.000Z',
    approvedBy: 'staff-002',
    firstRentDate: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'prop-003',
    name: 'Asokoro Villa',
    type: 'rental',
    status: 'fully_funded',
    phase: 'renting', // Fully funded, tenanted, paying out quarterly
    location: { state: 'FCT', city: 'Abuja', area: 'Asokoro' },
    developerId: 'dev-003',
    developerName: 'Brains & Hammers',
    totalValue: 200000000,
    unitPrice: 500000,
    totalUnits: 400,
    unitsSold: 400,
    investorCount: 89,
    yield: '16.0%',
    description: 'Premium 5-bedroom detached villa in Asokoro District, one of Abuja\'s most prestigious neighborhoods. Rented to a foreign embassy on a 3-year renewable lease. Fully funded with consistent quarterly payouts.',
    platformFeePercent: 3,
    managementFeePercent: 10,
    paystackSubaccountCode: 'ACCT_asokoro003',
    dvaAccountNumber: '9900034567',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Certificate of Occupancy', url: '/docs/prop-003/cofo.pdf', type: 'legal' },
      { name: 'Tenancy Agreement', url: '/docs/prop-003/tenancy.pdf', type: 'legal' },
      { name: 'Valuation Report', url: '/docs/prop-003/valuation.pdf', type: 'financial' },
    ],
    images: ['/images/prop-003/main.jpg', '/images/prop-003/garden.jpg', '/images/prop-003/interior.jpg'],
    createdAt: '2025-03-10T08:00:00.000Z',
    approvedAt: '2025-03-15T10:00:00.000Z',
    approvedBy: 'staff-001',
    firstRentDate: '2025-05-01T00:00:00.000Z',
  },
  {
    id: 'prop-005',
    name: 'Wuse 2 Apartments',
    type: 'rental',
    status: 'active',
    phase: 'vacant', // Built, but still looking for tenants
    location: { state: 'FCT', city: 'Abuja', area: 'Wuse 2' },
    developerId: 'dev-003',
    developerName: 'Brains & Hammers',
    totalValue: 95000000,
    unitPrice: 50000,
    totalUnits: 1900,
    unitsSold: 1420,
    investorCount: 387,
    yield: '12.8%',
    description: 'Modern 2 and 3 bedroom apartment block in Wuse 2, close to Aminu Kano Crescent. 16 units across 4 floors with basement parking, gym, and rooftop lounge. Construction complete, actively marketing to tenants.',
    platformFeePercent: 3,
    managementFeePercent: 10,
    paystackSubaccountCode: 'ACCT_wuse005',
    dvaAccountNumber: '9900056789',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Certificate of Occupancy', url: '/docs/prop-005/cofo.pdf', type: 'legal' },
      { name: 'Facility Management Contract', url: '/docs/prop-005/facility.pdf', type: 'legal' },
      { name: 'Rental Income Projection', url: '/docs/prop-005/projection.pdf', type: 'financial' },
    ],
    images: ['/images/prop-005/main.jpg', '/images/prop-005/lobby.jpg', '/images/prop-005/unit.jpg'],
    createdAt: '2025-07-20T10:00:00.000Z',
    approvedAt: '2025-07-25T15:00:00.000Z',
    approvedBy: 'staff-002',
  },
  {
    id: 'prop-007',
    name: 'Maitama Executive Suite',
    type: 'rental',
    status: 'completed',
    phase: 'completed', // Rental cycle done, all investors paid out
    location: { state: 'FCT', city: 'Abuja', area: 'Maitama' },
    developerId: 'dev-001',
    developerName: 'Saleem Goje Properties',
    totalValue: 175000000,
    unitPrice: 350000,
    totalUnits: 500,
    unitsSold: 500,
    investorCount: 67,
    yield: '15.2%',
    description: 'Luxury serviced apartment in Maitama District. 3-year investment cycle completed with all investors paid out. Total return of 46.8% over the investment period.',
    platformFeePercent: 3,
    managementFeePercent: 10,
    paystackSubaccountCode: 'ACCT_maitama007',
    dvaAccountNumber: '9900078901',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Certificate of Occupancy', url: '/docs/prop-007/cofo.pdf', type: 'legal' },
      { name: 'Final Audit Report', url: '/docs/prop-007/audit.pdf', type: 'financial' },
      { name: 'Completion Certificate', url: '/docs/prop-007/completion.pdf', type: 'project' },
    ],
    images: ['/images/prop-007/main.jpg', '/images/prop-007/suite.jpg'],
    createdAt: '2025-01-05T09:00:00.000Z',
    approvedAt: '2025-01-10T11:00:00.000Z',
    approvedBy: 'staff-001',
    firstRentDate: '2025-02-01T00:00:00.000Z',
  },
  {
    id: 'prop-009',
    name: 'Lokogoma Heights',
    type: 'rental',
    status: 'draft',
    phase: 'funding', // Not yet approved, will need to be funded first
    location: { state: 'FCT', city: 'Abuja', area: 'Lokogoma' },
    developerId: 'dev-002',
    developerName: 'Dan Mama Homes',
    totalValue: 85000000,
    unitPrice: 85000,
    totalUnits: 1000,
    unitsSold: 0,
    investorCount: 0,
    yield: '13.5%',
    description: 'Proposed 10-unit apartment development in Lokogoma District. Targeting young families with 2 and 3 bedroom options, children\'s play area, and community center. Still in planning phase.',
    platformFeePercent: 3,
    managementFeePercent: 10,
    paystackSubaccountCode: '',
    dvaAccountNumber: '',
    dvaBank: '',
    documents: [
      { name: 'Project Proposal', url: '/docs/prop-009/proposal.pdf', type: 'project' },
    ],
    images: ['/images/prop-009/concept.jpg'],
    createdAt: '2026-04-15T10:00:00.000Z',
    constructionProgress: 0,
    expectedCompletionDate: '2027-12-31T00:00:00.000Z',
  },

  // ── BUILD & SELL PROPERTIES ─────────────────────────────
  {
    id: 'prop-002',
    name: 'Kuje Smart Estate',
    type: 'build_sell',
    status: 'active',
    phase: 'construction', // Funded, under construction, will be SOLD (not rented)
    location: { state: 'FCT', city: 'Abuja', area: 'Kuje' },
    developerId: 'dev-002',
    developerName: 'Dan Mama Homes',
    totalValue: 120000000,
    unitPrice: 100000,
    totalUnits: 1200,
    unitsSold: 780,
    investorCount: 256,
    yield: '22.0%',
    description: 'A 20-unit smart estate in Kuje Area Council. 3-bedroom semi-detached bungalows with solar panels, water treatment, and fiber optic. Once built, units will be sold to end-buyers at market price. Investors share in the sale profit.',
    platformFeePercent: 3,
    managementFeePercent: 5,
    paystackSubaccountCode: 'ACCT_kuje002',
    dvaAccountNumber: '9900023456',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Survey Plan', url: '/docs/prop-002/survey.pdf', type: 'legal' },
      { name: 'Construction Timeline', url: '/docs/prop-002/timeline.pdf', type: 'project' },
      { name: 'Financial Projection', url: '/docs/prop-002/projection.pdf', type: 'financial' },
    ],
    images: ['/images/prop-002/render.jpg', '/images/prop-002/site.jpg'],
    createdAt: '2025-08-01T09:00:00.000Z',
    approvedAt: '2025-08-10T11:00:00.000Z',
    approvedBy: 'staff-002',
    constructionProgress: 45,
    expectedCompletionDate: '2026-12-31T00:00:00.000Z',
  },
  {
    id: 'prop-004',
    name: 'Jahi Mixed Use',
    type: 'build_sell',
    status: 'under_review',
    phase: 'funding', // Pending approval, will accept investors once approved
    location: { state: 'FCT', city: 'Abuja', area: 'Jahi' },
    developerId: 'dev-001',
    developerName: 'Saleem Goje Properties',
    totalValue: 150000000,
    unitPrice: 150000,
    totalUnits: 1000,
    unitsSold: 0,
    investorCount: 0,
    yield: '18.5%',
    description: 'Mixed-use development: 12 residential + 4 commercial spaces in Jahi. Developer builds and sells to end-buyers. Investors earn from the sale price premium over construction cost.',
    platformFeePercent: 3,
    managementFeePercent: 5,
    paystackSubaccountCode: '',
    dvaAccountNumber: '',
    dvaBank: '',
    documents: [
      { name: 'Survey Plan', url: '/docs/prop-004/survey.pdf', type: 'legal' },
      { name: 'Architectural Drawing', url: '/docs/prop-004/drawings.pdf', type: 'project' },
      { name: 'Cost Estimate', url: '/docs/prop-004/cost.pdf', type: 'financial' },
    ],
    images: ['/images/prop-004/render1.jpg', '/images/prop-004/render2.jpg'],
    createdAt: '2026-04-01T12:00:00.000Z',
    constructionProgress: 0,
    expectedCompletionDate: '2027-06-30T00:00:00.000Z',
  },
  {
    id: 'prop-008',
    name: 'Lekki Gardens Phase 3',
    type: 'build_sell',
    status: 'active',
    phase: 'selling', // Construction done, now selling units to end-buyers
    location: { state: 'Lagos', city: 'Lagos', area: 'Lekki' },
    developerId: 'dev-004',
    developerName: "Cappa & D'Alberto",
    totalValue: 200000000,
    unitPrice: 200000,
    totalUnits: 1000,
    unitsSold: 340,
    investorCount: 156,
    yield: '20.0%',
    description: 'Phase 3 of Lekki Gardens — 30 terraced duplexes. Construction is complete. Developer is now selling finished units to end-buyers at ₦45M-₦55M each. Once all sold, profit is distributed to investors.',
    platformFeePercent: 3,
    managementFeePercent: 5,
    paystackSubaccountCode: 'ACCT_lekki008',
    dvaAccountNumber: '9900089012',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Governor\'s Consent', url: '/docs/prop-008/consent.pdf', type: 'legal' },
      { name: 'Sales Progress Report', url: '/docs/prop-008/sales.pdf', type: 'project' },
      { name: 'Financial Model', url: '/docs/prop-008/model.pdf', type: 'financial' },
    ],
    images: ['/images/prop-008/render.jpg', '/images/prop-008/progress.jpg', '/images/prop-008/site.jpg'],
    createdAt: '2025-11-01T10:00:00.000Z',
    approvedAt: '2025-11-08T14:00:00.000Z',
    approvedBy: 'staff-002',
    constructionProgress: 100,
    expectedCompletionDate: '2026-09-30T00:00:00.000Z',
  },

  // ── LAND PROPERTIES ─────────────────────────────────────
  {
    id: 'prop-006',
    name: 'Kubwa Land Bank',
    type: 'land',
    status: 'active',
    phase: 'holding', // Land bought, holding for appreciation
    location: { state: 'FCT', city: 'Abuja', area: 'Kubwa' },
    developerId: 'dev-002',
    developerName: 'Dan Mama Homes',
    totalValue: 60000000,
    unitPrice: 60000,
    totalUnits: 1000,
    unitsSold: 650,
    investorCount: 198,
    yield: '25.0%',
    description: '5 hectares of titled land in Kubwa Extension along the new expressway corridor. Holding for appreciation as Abuja expands northward. Will be sold to developers or end-buyers at a premium.',
    platformFeePercent: 3,
    managementFeePercent: 0,
    paystackSubaccountCode: 'ACCT_kubwa006',
    dvaAccountNumber: '9900067890',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Right of Occupancy', url: '/docs/prop-006/rofo.pdf', type: 'legal' },
      { name: 'Survey Plan', url: '/docs/prop-006/survey.pdf', type: 'legal' },
      { name: 'Land Valuation', url: '/docs/prop-006/valuation.pdf', type: 'financial' },
    ],
    images: ['/images/prop-006/aerial.jpg', '/images/prop-006/site.jpg'],
    createdAt: '2025-09-10T08:00:00.000Z',
    approvedAt: '2025-09-15T12:00:00.000Z',
    approvedBy: 'staff-005',
  },
  {
    id: 'prop-010',
    name: 'Karsana Premium Plots',
    type: 'land',
    status: 'paused',
    phase: 'holding', // Holding, but paused due to dispute
    location: { state: 'FCT', city: 'Abuja', area: 'Karsana' },
    developerId: 'dev-001',
    developerName: 'Saleem Goje Properties',
    totalValue: 50000000,
    unitPrice: 50000,
    totalUnits: 1000,
    unitsSold: 420,
    investorCount: 135,
    yield: '30.0%',
    description: '3 hectares in Karsana District, divided into 15 residential plots. Investment paused pending boundary dispute resolution. Once resolved, plots will be sold individually to end-buyers.',
    platformFeePercent: 3,
    managementFeePercent: 0,
    paystackSubaccountCode: 'ACCT_karsana010',
    dvaAccountNumber: '9900001234',
    dvaBank: 'Wema Bank',
    documents: [
      { name: 'Right of Occupancy', url: '/docs/prop-010/rofo.pdf', type: 'legal' },
      { name: 'Dispute Summary', url: '/docs/prop-010/dispute.pdf', type: 'legal' },
    ],
    images: ['/images/prop-010/aerial.jpg'],
    createdAt: '2025-10-05T08:00:00.000Z',
    approvedAt: '2025-10-10T09:00:00.000Z',
    approvedBy: 'staff-005',
  },
];
