import type { Property } from '../types';

export const properties: Property[] = [
  {
    id: 'prop-1',
    name: 'Gwarinpa Luxury Duplex',
    type: 'rental',
    status: 'active',
    phase: 'renting',
    location: { state: 'FCT', city: 'Abuja', area: 'Gwarinpa' },
    developerId: 'dev-001',
    totalValue: 90_000_000,
    unitPrice: 150_000,
    totalUnits: 600,
    unitsSold: 432,
    investorCount: 432,
    description: 'Stunning 4-bedroom duplex in Gwarinpa with modern finishes, 24-hour power supply. Fully tenanted with verified annual rent of ₦4.2M.',
    platformFeePercent: 2,
    managementFeePercent: 10,
    documents: [
      { name: 'Certificate of Occupancy', url: '#', type: 'c_of_o' },
      { name: 'Building Plan', url: '#', type: 'building_plan' },
    ],
    images: [],
    createdAt: '2025-08-10T00:00:00Z',
    approvedAt: '2025-08-15T00:00:00Z',
    annualRent: 4_200_000,
    rentYield: 8.5,
    payoutFrequency: 'quarterly',
  },
  {
    id: 'prop-2',
    name: 'Wuse 2 Smart Homes',
    type: 'build_sell',
    status: 'active',
    phase: 'funding',
    location: { state: 'FCT', city: 'Abuja', area: 'Wuse 2' },
    developerId: 'dev-001',
    totalValue: 180_000_000,
    unitPrice: 75_000,
    totalUnits: 2400,
    unitsSold: 480,
    investorCount: 280,
    description: '6-unit smart home development in Wuse 2. Features home automation, solar power, and modern design. Early stage — 20% funded.',
    platformFeePercent: 2,
    managementFeePercent: 8,
    documents: [
      { name: 'Certificate of Occupancy', url: '#', type: 'c_of_o' },
      { name: 'Architectural Plan', url: '#', type: 'building_plan' },
    ],
    images: [],
    createdAt: '2026-01-20T00:00:00Z',
    approvedAt: '2026-01-25T00:00:00Z',
    buildCost: 130_000_000,
    estimatedSalePrice: 250_000_000,
    timelineMonths: 14,
    constructionProgress: 0,
    expectedCompletionDate: '2027-04-01',
  },
  {
    id: 'prop-3',
    name: 'Jabi Lake Terraces',
    type: 'rental',
    status: 'active',
    phase: 'renting',
    location: { state: 'FCT', city: 'Abuja', area: 'Jabi' },
    developerId: 'dev-001',
    totalValue: 150_000_000,
    unitPrice: 250_000,
    totalUnits: 600,
    unitsSold: 540,
    investorCount: 540,
    description: 'Premium 3-block terrace apartments overlooking Jabi Lake. Each block has 4 units. Currently generating ₦12M annual rent with 98% occupancy.',
    platformFeePercent: 2,
    managementFeePercent: 10,
    documents: [
      { name: 'Certificate of Occupancy', url: '#', type: 'c_of_o' },
      { name: 'Building Plan', url: '#', type: 'building_plan' },
      { name: "Governor's Consent", url: '#', type: 'governors_consent' },
    ],
    images: [],
    createdAt: '2025-07-05T00:00:00Z',
    approvedAt: '2025-07-10T00:00:00Z',
    annualRent: 12_000_000,
    rentYield: 10.2,
    payoutFrequency: 'quarterly',
  },
  {
    id: 'prop-4',
    name: 'Asokoro Executive Villa',
    type: 'rental',
    status: 'under_review',
    phase: 'funding',
    location: { state: 'FCT', city: 'Abuja', area: 'Asokoro' },
    developerId: 'dev-001',
    totalValue: 200_000_000,
    unitPrice: 500_000,
    totalUnits: 400,
    unitsSold: 0,
    investorCount: 0,
    description: '5-bedroom executive villa in the heart of Asokoro. Premium location near embassies. Expected to generate ₦18M in annual rent.',
    platformFeePercent: 2,
    managementFeePercent: 12,
    documents: [
      { name: 'Certificate of Occupancy', url: '#', type: 'c_of_o' },
    ],
    images: [],
    createdAt: '2026-04-20T00:00:00Z',
    annualRent: 18_000_000,
    rentYield: 9.0,
    payoutFrequency: 'quarterly',
  },
];
